//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AmbitProT.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MAIN_TEST_PANEL             102
#define IDD_TESTER_DLG                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_SFIS_DLG                    104
#define IDD_MYDAS_DLG                   105
#define IDR_HTML_DIALOGOFF              106
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_AmbitProTTYPE               129
#define IDD_DETAIL_LOG_DLG              130
#define IDI_FAIL                        132
#define IDI_PASS                        133
#define IDI_UNLINK                      134
#define IDI_LINK                        135
#define IDI_WARN                        137
#define IDD_VIR_SMO                     138
#define IDD_EQUIPMENT_DLG               140
#define IDI_AMBIT                       143
#define IDD_MAIN_CONTROL_PANEL          146
#define IDI_AMBER1                      150
#define IDI_PTLANGREEN1                 164
#define IDI_PTWANGREEN1                 166
#define IDI_FTLANGREEN1                 167
#define IDI_FTWANGREEN1                 168
#define IDI_GREEN1                      169
#define IDI_AMBER2                      170
#define IDD_AMBER                       192
#define IDD_DIALOG_LED                  192
#define IDB_BITMAP1                     197
#define IDD_FTWANGREEN2                 199
#define IDB_AMBER                       199
#define IDB_GREEN                       200
#define IDB_FTLANGREEN                  201
#define IDB_FTWANGREEN                  202
#define IDB_PTLANGREEN                  203
#define IDB_PTWANGREEN                  204
#define IDB_BLINK                       206
#define IDB_OFF                         207
#define IDB_PANELDOWN                   208
#define IDD_DIALOG_MAIN                 209
#define IDD_DIALOG_CONF                 210
#define IDI_SMO_OFF                     218
#define IDI_EQUI_OFF                    219
#define IDI_SFIS_OFF                    220
#define IDI_SMO_ON                      221
#define IDI_SFIS_ON                     222
#define IDI_EQUI_ON                     223
#define IDD_DIALOG_USER                 223
#define IDI_PTS_ON                      224
#define IDD_DIALOG1                     224
#define IDD_DIALOG_RTM                  224
#define IDI_PTS_OFF                     225
#define IDB_BITMAP2                     225
#define IDB_ANALYSE                     225
#define IDI_RTM_OFF                     226
#define IDI_RTM_ON                      227
#define IDC_STA_NAME                    1001
#define IDC_UUT_PNNAME                  1002
#define IDC_BUTTON1                     1003
#define IDC_BTN_SWTO_TESTER             1004
#define IDC_BTN_SHOWLOG                 1004
#define IDC_BUTTON2                     1004
#define IDC_BTN_SWTO_MT_DLG             1005
#define IDC_BTN_SWTO_MYDAS_DLG          1006
#define IDC_BTN_SWTO_SFIS_DLG           1007
#define IDC_BIG_RESULT                  1008
#define IDC_BTN_START_TEST              1009
#define IDC_BTN_SFIS                    1012
#define IDC_STC_TESTTIME                1013
#define IDC_BTN_SWITCH_SHOW             1015
#define IDC_STC_CURRENT_ITEM            1016
#define IDC_STC_ERROR_CODE              1017
#define IDC_STC_SMALL_RESULT            1018
#define IDC_STC_MYDAS_STATUS            1019
#define IDC_STC_CONNECT_FLAG            1020
#define IDC_STC_SEND_RECORD_NUM         1021
#define IDC_DCT                         1022
#define IDC_SFIS_SHOW                   1023
#define IDC_LINK_PICTURE                1024
#define IDC_EDIT_IDC                    1026
#define IDC_SMO_PICTURE                 1027
#define IDC_SFIS_LINK                   1034
#define IDC_UUT_SFIS_INFO               1035
#define IDC_EQUIP_STATUS                1037
#define IDC_EQUIP_PICTURE               1038
#define IDC_STATIC_ES                   1039
#define IDC_VIR_SEND                    1040
#define IDC_VIR_SMO_ITEM1               1042
#define IDC_VIR_SMO_ITEM2               1043
#define IDC_BUTTON3                     1043
#define IDC_VIRT_OPEN                   1043
#define IDC_VIR_SMO_ITEM3               1044
#define IDC_BTN_QUERY                   1044
#define IDC_VIR_SMO_ITEM4               1045
#define IDC_BTN_CLEAR                   1045
#define IDC_EQUIP_LIST                  1046
#define IDC_EDEQUIP_PWD                 1047
#define IDC_EDEQUIP_USER                1048
#define IDC_EQUIP_CLOSE                 1048
#define IDC_EQUIP_DLG_CLOSE             1048
#define IDC_EQUIP_DLG_OPEN              1049
#define IDC_EDIT1                       1050
#define IDC_USER_ID                     1050
#define IDC_BUTTON4                     1051
#define IDC_BORDER1                     1052
#define IDC_BORDER2                     1053
#define IDC_BORDER3                     1054
#define IDC_BORDER4                     1055
#define IDC_EDIT_UPBORDER               1056
#define IDC_EDIT_DNBORDER               1057
#define IDC_AMBER_PIC                   1060
#define IDC_                            1061
#define IDC_GREEN_PIC                   1061
#define IDC_LED_OFF                     1062
#define IDC_PT_WAN                      1063
#define IDC_PT_LAN                      1064
#define IDC_FT_WAN                      1065
#define IDC_FT_LAN                      1066
#define IDC_DOWN_PIC                    1067
#define IDC_BLINK_PIC                   1068
#define IDC_TAB1                        1069
#define IDC_BUTTON_LOG                  1070
#define IDC_DATETIMEPICKER1             1072
#define IDC_ITEM_MODIFY                 1073
#define IDC_TESTER_UTI                  1074
#define IDC_PIC_SFIS                    1075
#define IDC_PIC_SMO                     1076
#define IDC_PIC_EQUIP                   1077
#define IDC_TIME                        1078
#define IDC_PIC_PTS                     1079
#define IDC_STATIC_SCAN                 1080
#define IDC_STATIC_IN                   1081
#define IDC_STATIC_OUT                  1082
#define IDC_PIC_RTM                     1083
#define IDC_LIST1                       1084
#define IDC_ITEM_TWO                    1085
#define IDC_BUTTON_TWO                  1086
#define IDC_ITEM                        1087
#define IDC_STATIC_INDI                 1088
#define IDC_STATIC_SFIS                 1089
#define IDC_CHECK_ONE                   1090
#define IDC_CHECK_TWO                   1091
#define IDC_TESTER_UTI2                 1092
#define IDC_SN                          1094
#define IDC_LIST2                       1095
#define IDC_LIST3                       1096
#define IDC_LIST4                       1097
#define IDC_LIST5                       1098
#define IDC_LIST6                       1099
#define IDC_ERRORCODE                   1100
#define IDC_CUSTOM1                     1101
#define IDC_ANALYSE_PIC                 1102
#define ID_EDIT_MODIFY                  32771
#define ID_VIEW_COUNT                   32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
